\hypertarget{_mock_failure_test_8cpp}{}\section{thirdparty/cpputest/tests/\+Cpp\+U\+Test\+Ext/\+Mock\+Failure\+Test.cpp 파일 참조}
\label{_mock_failure_test_8cpp}\index{thirdparty/cpputest/tests/\+Cpp\+U\+Test\+Ext/\+Mock\+Failure\+Test.\+cpp@{thirdparty/cpputest/tests/\+Cpp\+U\+Test\+Ext/\+Mock\+Failure\+Test.\+cpp}}
{\ttfamily \#include \char`\"{}Cpp\+U\+Test/\+Test\+Harness.\+h\char`\"{}}\\*
{\ttfamily \#include \char`\"{}Cpp\+U\+Test\+Ext/\+Mock\+Failure.\+h\char`\"{}}\\*
{\ttfamily \#include \char`\"{}Cpp\+U\+Test\+Ext/\+Mock\+Checked\+Expected\+Call.\+h\char`\"{}}\\*
{\ttfamily \#include \char`\"{}Cpp\+U\+Test\+Ext/\+Mock\+Expected\+Calls\+List.\+h\char`\"{}}\\*
{\ttfamily \#include \char`\"{}Mock\+Failure\+Reporter\+For\+Test.\+h\char`\"{}}\\*
Mock\+Failure\+Test.\+cpp에 대한 include 의존 그래프
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{_mock_failure_test_8cpp__incl}
\end{center}
\end{figure}
\subsection*{함수}
\begin{DoxyCompactItemize}
\item 
\hyperlink{_mock_failure_test_8cpp_a3b989a8079863b123e286dfbeebad578}{T\+E\+S\+T\+\_\+\+G\+R\+O\+UP} (Mock\+Failure\+Test)
\item 
\hyperlink{_mock_failure_test_8cpp_a1f9777438cdb02ad03f5001de10623c7}{T\+E\+ST} (Mock\+Failure\+Test, no\+Error\+Failure\+Something\+Gone\+Wrong)
\item 
\hyperlink{_mock_failure_test_8cpp_a5bcd0ca638207b77d5746991246487dc}{T\+E\+ST} (Mock\+Failure\+Test, unexpected\+Call\+Happened)
\item 
\hyperlink{_mock_failure_test_8cpp_a36ec4467729b05e6db5ac52c2b8c64ed}{T\+E\+ST} (Mock\+Failure\+Test, expected\+Call\+Did\+Not\+Happen)
\item 
\hyperlink{_mock_failure_test_8cpp_ae38a40a0a7c74b1bc5203194f63ca184}{T\+E\+ST} (Mock\+Failure\+Test, Mock\+Unexpected\+Nth\+Additional\+Call\+Failure)
\item 
\hyperlink{_mock_failure_test_8cpp_a6f349c994f7ebbba20c3487346686bbc}{T\+E\+ST} (Mock\+Failure\+Test, \hyperlink{class_mock_unexpected_input_parameter_failure}{Mock\+Unexpected\+Input\+Parameter\+Failure})
\item 
\hyperlink{_mock_failure_test_8cpp_ae8f4c44dc390fb839fa839406e4a7003}{T\+E\+ST} (Mock\+Failure\+Test, \hyperlink{class_mock_unexpected_output_parameter_failure}{Mock\+Unexpected\+Output\+Parameter\+Failure})
\item 
\hyperlink{_mock_failure_test_8cpp_a23a75efa0a24aa06167299ada721ed55}{T\+E\+ST} (Mock\+Failure\+Test, Mock\+Unexpected\+Parameter\+Value\+Failure)
\item 
\hyperlink{_mock_failure_test_8cpp_abc7859dd9ae622a43df44d3fe121fdcd}{T\+E\+ST} (Mock\+Failure\+Test, \hyperlink{class_mock_expected_parameter_didnt_happen_failure}{Mock\+Expected\+Parameter\+Didnt\+Happen\+Failure})
\item 
\hyperlink{_mock_failure_test_8cpp_ade8fce18c5592014b4485603069e805b}{T\+E\+ST} (Mock\+Failure\+Test, \hyperlink{class_mock_no_way_to_compare_custom_type_failure}{Mock\+No\+Way\+To\+Compare\+Custom\+Type\+Failure})
\item 
\hyperlink{_mock_failure_test_8cpp_addf2efef7f65ebc4816e6e9adffee168}{T\+E\+ST} (Mock\+Failure\+Test, \hyperlink{class_mock_unexpected_object_failure}{Mock\+Unexpected\+Object\+Failure})
\item 
\hyperlink{_mock_failure_test_8cpp_aca94e143af3b376fe013f99e92c378b7}{T\+E\+ST} (Mock\+Failure\+Test, \hyperlink{class_mock_expected_object_didnt_happen_failure}{Mock\+Expected\+Object\+Didnt\+Happen\+Failure})
\end{DoxyCompactItemize}


\subsection{함수 문서화}
\index{Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}!T\+E\+ST@{T\+E\+ST}}
\index{T\+E\+ST@{T\+E\+ST}!Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}}
\subsubsection[{\texorpdfstring{T\+E\+S\+T(\+Mock\+Failure\+Test, no\+Error\+Failure\+Something\+Gone\+Wrong)}{TEST(MockFailureTest, noErrorFailureSomethingGoneWrong)}}]{\setlength{\rightskip}{0pt plus 5cm}T\+E\+ST (
\begin{DoxyParamCaption}
\item[{Mock\+Failure\+Test}]{, }
\item[{no\+Error\+Failure\+Something\+Gone\+Wrong}]{}
\end{DoxyParamCaption}
)}\hypertarget{_mock_failure_test_8cpp_a1f9777438cdb02ad03f5001de10623c7}{}\label{_mock_failure_test_8cpp_a1f9777438cdb02ad03f5001de10623c7}


Mock\+Failure\+Test.\+cpp 파일의 83 번째 라인에서 정의되었습니다.


\begin{DoxyCode}
84 \{
85     \hyperlink{class_mock_failure}{MockFailure} failure(\hyperlink{class_utest_shell_afeb97f1f06324a42444c71b412655122}{UtestShell::getCurrent}());
86     \hyperlink{_utest_macros_8h_ade1dda09c948fee9ceb853bc6dd5f3cb}{STRCMP\_EQUAL}(\textcolor{stringliteral}{"Test failed with MockFailure without an error! Something went seriously
       wrong."}, failure.getMessage().asCharString());
87 \}
\end{DoxyCode}


이 함수 내부에서 호출하는 함수들에 대한 그래프입니다.\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{_mock_failure_test_8cpp_a1f9777438cdb02ad03f5001de10623c7_cgraph}
\end{center}
\end{figure}


\index{Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}!T\+E\+ST@{T\+E\+ST}}
\index{T\+E\+ST@{T\+E\+ST}!Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}}
\subsubsection[{\texorpdfstring{T\+E\+S\+T(\+Mock\+Failure\+Test, unexpected\+Call\+Happened)}{TEST(MockFailureTest, unexpectedCallHappened)}}]{\setlength{\rightskip}{0pt plus 5cm}T\+E\+ST (
\begin{DoxyParamCaption}
\item[{Mock\+Failure\+Test}]{, }
\item[{unexpected\+Call\+Happened}]{}
\end{DoxyParamCaption}
)}\hypertarget{_mock_failure_test_8cpp_a5bcd0ca638207b77d5746991246487dc}{}\label{_mock_failure_test_8cpp_a5bcd0ca638207b77d5746991246487dc}


Mock\+Failure\+Test.\+cpp 파일의 89 번째 라인에서 정의되었습니다.


\begin{DoxyCode}
90 \{
91     \hyperlink{class_mock_unexpected_call_happened_failure}{MockUnexpectedCallHappenedFailure} failure(
      \hyperlink{class_utest_shell_afeb97f1f06324a42444c71b412655122}{UtestShell::getCurrent}(), \textcolor{stringliteral}{"foobar"}, *list);
92     \hyperlink{_utest_macros_8h_ade1dda09c948fee9ceb853bc6dd5f3cb}{STRCMP\_EQUAL}(\textcolor{stringliteral}{"Mock Failure: Unexpected call to function: foobar\(\backslash\)n"}
93                  \textcolor{stringliteral}{"\(\backslash\)tEXPECTED calls that did NOT happen:\(\backslash\)n"}
94                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)t<none>\(\backslash\)n"}
95                  \textcolor{stringliteral}{"\(\backslash\)tACTUAL calls that did happen (in call order):\(\backslash\)n"}
96                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)t<none>"}, failure.getMessage().asCharString());
97 \}
\end{DoxyCode}


이 함수 내부에서 호출하는 함수들에 대한 그래프입니다.\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{_mock_failure_test_8cpp_a5bcd0ca638207b77d5746991246487dc_cgraph}
\end{center}
\end{figure}


\index{Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}!T\+E\+ST@{T\+E\+ST}}
\index{T\+E\+ST@{T\+E\+ST}!Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}}
\subsubsection[{\texorpdfstring{T\+E\+S\+T(\+Mock\+Failure\+Test, expected\+Call\+Did\+Not\+Happen)}{TEST(MockFailureTest, expectedCallDidNotHappen)}}]{\setlength{\rightskip}{0pt plus 5cm}T\+E\+ST (
\begin{DoxyParamCaption}
\item[{Mock\+Failure\+Test}]{, }
\item[{expected\+Call\+Did\+Not\+Happen}]{}
\end{DoxyParamCaption}
)}\hypertarget{_mock_failure_test_8cpp_a36ec4467729b05e6db5ac52c2b8c64ed}{}\label{_mock_failure_test_8cpp_a36ec4467729b05e6db5ac52c2b8c64ed}


Mock\+Failure\+Test.\+cpp 파일의 99 번째 라인에서 정의되었습니다.


\begin{DoxyCode}
100 \{
101     call1->withName(\textcolor{stringliteral}{"foobar"});
102     call2->withName(\textcolor{stringliteral}{"world"}).withParameter(\textcolor{stringliteral}{"boo"}, 2).withParameter(\textcolor{stringliteral}{"hello"}, \textcolor{stringliteral}{"world"});
103     call3->withName(\textcolor{stringliteral}{"haphaphap"});
104     call3->callWasMade(1);
105     addAllToList();
106 
107     \hyperlink{class_mock_expected_calls_didnt_happen_failure}{MockExpectedCallsDidntHappenFailure} failure(
      \hyperlink{class_utest_shell_afeb97f1f06324a42444c71b412655122}{UtestShell::getCurrent}(), *list);
108     \hyperlink{_utest_macros_8h_ade1dda09c948fee9ceb853bc6dd5f3cb}{STRCMP\_EQUAL}(\textcolor{stringliteral}{"Mock Failure: Expected call did not happen.\(\backslash\)n"}
109                  \textcolor{stringliteral}{"\(\backslash\)tEXPECTED calls that did NOT happen:\(\backslash\)n"}
110                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tfoobar -> no parameters\(\backslash\)n"}
111                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tworld -> int boo: <2 (0x2)>, const char* hello: <world>\(\backslash\)n"}
112                  \textcolor{stringliteral}{"\(\backslash\)tACTUAL calls that did happen (in call order):\(\backslash\)n"}
113                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)thaphaphap -> no parameters"}, failure.getMessage().asCharString());
114 \}
\end{DoxyCode}


이 함수 내부에서 호출하는 함수들에 대한 그래프입니다.\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{_mock_failure_test_8cpp_a36ec4467729b05e6db5ac52c2b8c64ed_cgraph}
\end{center}
\end{figure}


\index{Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}!T\+E\+ST@{T\+E\+ST}}
\index{T\+E\+ST@{T\+E\+ST}!Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}}
\subsubsection[{\texorpdfstring{T\+E\+S\+T(\+Mock\+Failure\+Test, Mock\+Unexpected\+Nth\+Additional\+Call\+Failure)}{TEST(MockFailureTest, MockUnexpectedNthAdditionalCallFailure)}}]{\setlength{\rightskip}{0pt plus 5cm}T\+E\+ST (
\begin{DoxyParamCaption}
\item[{Mock\+Failure\+Test}]{, }
\item[{Mock\+Unexpected\+Nth\+Additional\+Call\+Failure}]{}
\end{DoxyParamCaption}
)}\hypertarget{_mock_failure_test_8cpp_ae38a40a0a7c74b1bc5203194f63ca184}{}\label{_mock_failure_test_8cpp_ae38a40a0a7c74b1bc5203194f63ca184}


Mock\+Failure\+Test.\+cpp 파일의 116 번째 라인에서 정의되었습니다.


\begin{DoxyCode}
117 \{
118     checkUnexpectedNthCallMessage(2, \textcolor{stringliteral}{"2nd"});
119     checkUnexpectedNthCallMessage(3, \textcolor{stringliteral}{"3rd"});
120     checkUnexpectedNthCallMessage(4, \textcolor{stringliteral}{"4th"});
121     checkUnexpectedNthCallMessage(11, \textcolor{stringliteral}{"11th"});
122     checkUnexpectedNthCallMessage(12, \textcolor{stringliteral}{"12th"});
123     checkUnexpectedNthCallMessage(13, \textcolor{stringliteral}{"13th"});
124     checkUnexpectedNthCallMessage(14, \textcolor{stringliteral}{"14th"});
125     checkUnexpectedNthCallMessage(21, \textcolor{stringliteral}{"21st"});
126     checkUnexpectedNthCallMessage(22, \textcolor{stringliteral}{"22nd"});
127     checkUnexpectedNthCallMessage(23, \textcolor{stringliteral}{"23rd"});
128 \}
\end{DoxyCode}
\index{Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}!T\+E\+ST@{T\+E\+ST}}
\index{T\+E\+ST@{T\+E\+ST}!Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}}
\subsubsection[{\texorpdfstring{T\+E\+S\+T(\+Mock\+Failure\+Test, Mock\+Unexpected\+Input\+Parameter\+Failure)}{TEST(MockFailureTest, MockUnexpectedInputParameterFailure)}}]{\setlength{\rightskip}{0pt plus 5cm}T\+E\+ST (
\begin{DoxyParamCaption}
\item[{Mock\+Failure\+Test}]{, }
\item[{{\bf Mock\+Unexpected\+Input\+Parameter\+Failure}}]{}
\end{DoxyParamCaption}
)}\hypertarget{_mock_failure_test_8cpp_a6f349c994f7ebbba20c3487346686bbc}{}\label{_mock_failure_test_8cpp_a6f349c994f7ebbba20c3487346686bbc}


Mock\+Failure\+Test.\+cpp 파일의 130 번째 라인에서 정의되었습니다.


\begin{DoxyCode}
131 \{
132     call1->withName(\textcolor{stringliteral}{"foo"}).withParameter(\textcolor{stringliteral}{"boo"}, 2);
133     call2->withName(\textcolor{stringliteral}{"foo"}).withParameter(\textcolor{stringliteral}{"boo"}, 3.3);
134     call3->withName(\textcolor{stringliteral}{"unrelated"});
135     addAllToList();
136 
137     \hyperlink{class_mock_named_value}{MockNamedValue} actualParameter(\textcolor{stringliteral}{"bar"});
138     actualParameter.setValue(2);
139 
140     \hyperlink{class_mock_unexpected_input_parameter_failure}{MockUnexpectedInputParameterFailure} failure(
      \hyperlink{class_utest_shell_afeb97f1f06324a42444c71b412655122}{UtestShell::getCurrent}(), \textcolor{stringliteral}{"foo"}, actualParameter, *list);
141     \hyperlink{_utest_macros_8h_ade1dda09c948fee9ceb853bc6dd5f3cb}{STRCMP\_EQUAL}(\textcolor{stringliteral}{"Mock Failure: Unexpected parameter name to function \(\backslash\)"foo\(\backslash\)": bar\(\backslash\)n"}
142                  \textcolor{stringliteral}{"\(\backslash\)tEXPECTED calls that DID NOT happen related to function: foo\(\backslash\)n"}
143                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tfoo -> int boo: <2 (0x2)>\(\backslash\)n"}
144                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tfoo -> double boo: <3.3>\(\backslash\)n"}
145                  \textcolor{stringliteral}{"\(\backslash\)tACTUAL calls that DID happen related to function: foo\(\backslash\)n"}
146                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)t<none>\(\backslash\)n"}
147                  \textcolor{stringliteral}{"\(\backslash\)tACTUAL unexpected parameter passed to function: foo\(\backslash\)n"}
148                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tint bar: <2 (0x2)>"}, failure.getMessage().asCharString());
149 \}
\end{DoxyCode}


이 함수 내부에서 호출하는 함수들에 대한 그래프입니다.\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{_mock_failure_test_8cpp_a6f349c994f7ebbba20c3487346686bbc_cgraph}
\end{center}
\end{figure}


\index{Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}!T\+E\+ST@{T\+E\+ST}}
\index{T\+E\+ST@{T\+E\+ST}!Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}}
\subsubsection[{\texorpdfstring{T\+E\+S\+T(\+Mock\+Failure\+Test, Mock\+Unexpected\+Output\+Parameter\+Failure)}{TEST(MockFailureTest, MockUnexpectedOutputParameterFailure)}}]{\setlength{\rightskip}{0pt plus 5cm}T\+E\+ST (
\begin{DoxyParamCaption}
\item[{Mock\+Failure\+Test}]{, }
\item[{{\bf Mock\+Unexpected\+Output\+Parameter\+Failure}}]{}
\end{DoxyParamCaption}
)}\hypertarget{_mock_failure_test_8cpp_ae8f4c44dc390fb839fa839406e4a7003}{}\label{_mock_failure_test_8cpp_ae8f4c44dc390fb839fa839406e4a7003}


Mock\+Failure\+Test.\+cpp 파일의 151 번째 라인에서 정의되었습니다.


\begin{DoxyCode}
152 \{
153     \textcolor{keywordtype}{int} out1;
154     \textcolor{keywordtype}{int} out2;
155     call1->withName(\textcolor{stringliteral}{"foo"}).withOutputParameterReturning(\textcolor{stringliteral}{"boo"}, &out1, \textcolor{keyword}{sizeof}(out1));
156     call2->withName(\textcolor{stringliteral}{"foo"}).withOutputParameterReturning(\textcolor{stringliteral}{"boo"}, &out2, \textcolor{keyword}{sizeof}(out2));
157     call3->withName(\textcolor{stringliteral}{"unrelated"});
158     addAllToList();
159 
160     \hyperlink{class_mock_named_value}{MockNamedValue} actualParameter(\textcolor{stringliteral}{"bar"});
161     actualParameter.setValue((\textcolor{keywordtype}{void} *)0x123);
162 
163     \hyperlink{class_mock_unexpected_output_parameter_failure}{MockUnexpectedOutputParameterFailure} failure(
      \hyperlink{class_utest_shell_afeb97f1f06324a42444c71b412655122}{UtestShell::getCurrent}(), \textcolor{stringliteral}{"foo"}, actualParameter, *list);
164     \hyperlink{_utest_macros_8h_ade1dda09c948fee9ceb853bc6dd5f3cb}{STRCMP\_EQUAL}(\textcolor{stringliteral}{"Mock Failure: Unexpected output parameter name to function \(\backslash\)"foo\(\backslash\)": bar\(\backslash\)n"}
165                  \textcolor{stringliteral}{"\(\backslash\)tEXPECTED calls that DID NOT happen related to function: foo\(\backslash\)n"}
166                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tfoo -> const void* boo: <output>\(\backslash\)n"}
167                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tfoo -> const void* boo: <output>\(\backslash\)n"}
168                  \textcolor{stringliteral}{"\(\backslash\)tACTUAL calls that DID happen related to function: foo\(\backslash\)n"}
169                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)t<none>\(\backslash\)n"}
170                  \textcolor{stringliteral}{"\(\backslash\)tACTUAL unexpected output parameter passed to function: foo\(\backslash\)n"}
171                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tvoid* bar"}, failure.getMessage().asCharString());
172 \}
\end{DoxyCode}


이 함수 내부에서 호출하는 함수들에 대한 그래프입니다.\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{_mock_failure_test_8cpp_ae8f4c44dc390fb839fa839406e4a7003_cgraph}
\end{center}
\end{figure}


\index{Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}!T\+E\+ST@{T\+E\+ST}}
\index{T\+E\+ST@{T\+E\+ST}!Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}}
\subsubsection[{\texorpdfstring{T\+E\+S\+T(\+Mock\+Failure\+Test, Mock\+Unexpected\+Parameter\+Value\+Failure)}{TEST(MockFailureTest, MockUnexpectedParameterValueFailure)}}]{\setlength{\rightskip}{0pt plus 5cm}T\+E\+ST (
\begin{DoxyParamCaption}
\item[{Mock\+Failure\+Test}]{, }
\item[{Mock\+Unexpected\+Parameter\+Value\+Failure}]{}
\end{DoxyParamCaption}
)}\hypertarget{_mock_failure_test_8cpp_a23a75efa0a24aa06167299ada721ed55}{}\label{_mock_failure_test_8cpp_a23a75efa0a24aa06167299ada721ed55}


Mock\+Failure\+Test.\+cpp 파일의 174 번째 라인에서 정의되었습니다.


\begin{DoxyCode}
175 \{
176     call1->withName(\textcolor{stringliteral}{"foo"}).withParameter(\textcolor{stringliteral}{"boo"}, 2);
177     call2->withName(\textcolor{stringliteral}{"foo"}).withParameter(\textcolor{stringliteral}{"boo"}, 10);
178     call3->withName(\textcolor{stringliteral}{"unrelated"});
179     addAllToList();
180 
181     \hyperlink{class_mock_named_value}{MockNamedValue} actualParameter(\textcolor{stringliteral}{"boo"});
182     actualParameter.setValue(20);
183 
184     \hyperlink{class_mock_unexpected_input_parameter_failure}{MockUnexpectedInputParameterFailure} failure(
      \hyperlink{class_utest_shell_afeb97f1f06324a42444c71b412655122}{UtestShell::getCurrent}(), \textcolor{stringliteral}{"foo"}, actualParameter, *list);
185     \hyperlink{_utest_macros_8h_ade1dda09c948fee9ceb853bc6dd5f3cb}{STRCMP\_EQUAL}(\textcolor{stringliteral}{"Mock Failure: Unexpected parameter value to parameter \(\backslash\)"boo\(\backslash\)" to function \(\backslash\)"
      foo\(\backslash\)": <20 (0x14)>\(\backslash\)n"}
186                  \textcolor{stringliteral}{"\(\backslash\)tEXPECTED calls that DID NOT happen related to function: foo\(\backslash\)n"}
187                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tfoo -> int boo: <2 (0x2)>\(\backslash\)n"}
188                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tfoo -> int boo: <10 (0xa)>\(\backslash\)n"}
189                  \textcolor{stringliteral}{"\(\backslash\)tACTUAL calls that DID happen related to function: foo\(\backslash\)n"}
190                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)t<none>\(\backslash\)n"}
191                  \textcolor{stringliteral}{"\(\backslash\)tACTUAL unexpected parameter passed to function: foo\(\backslash\)n"}
192                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tint boo: <20 (0x14)>"}, failure.getMessage().asCharString());
193 \}
\end{DoxyCode}


이 함수 내부에서 호출하는 함수들에 대한 그래프입니다.\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{_mock_failure_test_8cpp_a23a75efa0a24aa06167299ada721ed55_cgraph}
\end{center}
\end{figure}


\index{Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}!T\+E\+ST@{T\+E\+ST}}
\index{T\+E\+ST@{T\+E\+ST}!Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}}
\subsubsection[{\texorpdfstring{T\+E\+S\+T(\+Mock\+Failure\+Test, Mock\+Expected\+Parameter\+Didnt\+Happen\+Failure)}{TEST(MockFailureTest, MockExpectedParameterDidntHappenFailure)}}]{\setlength{\rightskip}{0pt plus 5cm}T\+E\+ST (
\begin{DoxyParamCaption}
\item[{Mock\+Failure\+Test}]{, }
\item[{{\bf Mock\+Expected\+Parameter\+Didnt\+Happen\+Failure}}]{}
\end{DoxyParamCaption}
)}\hypertarget{_mock_failure_test_8cpp_abc7859dd9ae622a43df44d3fe121fdcd}{}\label{_mock_failure_test_8cpp_abc7859dd9ae622a43df44d3fe121fdcd}


Mock\+Failure\+Test.\+cpp 파일의 195 번째 라인에서 정의되었습니다.


\begin{DoxyCode}
196 \{
197     call1->withName(\textcolor{stringliteral}{"foo"}).withParameter(\textcolor{stringliteral}{"bar"}, 2).withParameter(\textcolor{stringliteral}{"boo"}, \textcolor{stringliteral}{"str"});
198     call2->withName(\textcolor{stringliteral}{"foo"}).withParameter(\textcolor{stringliteral}{"bar"}, 10).withParameter(\textcolor{stringliteral}{"boo"}, \textcolor{stringliteral}{"bleh"});
199     call2->callWasMade(1);
200     call2->inputParameterWasPassed(\textcolor{stringliteral}{"bar"});
201     call2->inputParameterWasPassed(\textcolor{stringliteral}{"boo"});
202     call3->withName(\textcolor{stringliteral}{"unrelated"});
203     addAllToList();
204 
205     \hyperlink{class_mock_expected_parameter_didnt_happen_failure}{MockExpectedParameterDidntHappenFailure} failure(
      \hyperlink{class_utest_shell_afeb97f1f06324a42444c71b412655122}{UtestShell::getCurrent}(), \textcolor{stringliteral}{"foo"}, *list);
206     \hyperlink{_utest_macros_8h_ade1dda09c948fee9ceb853bc6dd5f3cb}{STRCMP\_EQUAL}(\textcolor{stringliteral}{"Mock Failure: Expected parameter for function \(\backslash\)"foo\(\backslash\)" did not happen.\(\backslash\)n"}
207                  \textcolor{stringliteral}{"\(\backslash\)tEXPECTED calls that DID NOT happen related to function: foo\(\backslash\)n"}
208                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tfoo -> int bar: <2 (0x2)>, const char* boo: <str>\(\backslash\)n"}
209                  \textcolor{stringliteral}{"\(\backslash\)tACTUAL calls that DID happen related to function: foo\(\backslash\)n"}
210                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tfoo -> int bar: <10 (0xa)>, const char* boo: <bleh>\(\backslash\)n"}
211                  \textcolor{stringliteral}{"\(\backslash\)tMISSING parameters that didn't happen:\(\backslash\)n"}
212                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)tint bar, const char* boo"}, failure.getMessage().asCharString());
213 \}
\end{DoxyCode}


이 함수 내부에서 호출하는 함수들에 대한 그래프입니다.\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{_mock_failure_test_8cpp_abc7859dd9ae622a43df44d3fe121fdcd_cgraph}
\end{center}
\end{figure}


\index{Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}!T\+E\+ST@{T\+E\+ST}}
\index{T\+E\+ST@{T\+E\+ST}!Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}}
\subsubsection[{\texorpdfstring{T\+E\+S\+T(\+Mock\+Failure\+Test, Mock\+No\+Way\+To\+Compare\+Custom\+Type\+Failure)}{TEST(MockFailureTest, MockNoWayToCompareCustomTypeFailure)}}]{\setlength{\rightskip}{0pt plus 5cm}T\+E\+ST (
\begin{DoxyParamCaption}
\item[{Mock\+Failure\+Test}]{, }
\item[{{\bf Mock\+No\+Way\+To\+Compare\+Custom\+Type\+Failure}}]{}
\end{DoxyParamCaption}
)}\hypertarget{_mock_failure_test_8cpp_ade8fce18c5592014b4485603069e805b}{}\label{_mock_failure_test_8cpp_ade8fce18c5592014b4485603069e805b}


Mock\+Failure\+Test.\+cpp 파일의 215 번째 라인에서 정의되었습니다.


\begin{DoxyCode}
216 \{
217     \hyperlink{class_mock_no_way_to_compare_custom_type_failure}{MockNoWayToCompareCustomTypeFailure} failure(
      \hyperlink{class_utest_shell_afeb97f1f06324a42444c71b412655122}{UtestShell::getCurrent}(), \textcolor{stringliteral}{"myType"});
218     \hyperlink{_utest_macros_8h_ade1dda09c948fee9ceb853bc6dd5f3cb}{STRCMP\_EQUAL}(\textcolor{stringliteral}{"MockFailure: No way to compare type <myType>. Please install a
       MockNamedValueComparator."}, failure.getMessage().asCharString());
219 \}
\end{DoxyCode}


이 함수 내부에서 호출하는 함수들에 대한 그래프입니다.\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{_mock_failure_test_8cpp_ade8fce18c5592014b4485603069e805b_cgraph}
\end{center}
\end{figure}


\index{Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}!T\+E\+ST@{T\+E\+ST}}
\index{T\+E\+ST@{T\+E\+ST}!Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}}
\subsubsection[{\texorpdfstring{T\+E\+S\+T(\+Mock\+Failure\+Test, Mock\+Unexpected\+Object\+Failure)}{TEST(MockFailureTest, MockUnexpectedObjectFailure)}}]{\setlength{\rightskip}{0pt plus 5cm}T\+E\+ST (
\begin{DoxyParamCaption}
\item[{Mock\+Failure\+Test}]{, }
\item[{{\bf Mock\+Unexpected\+Object\+Failure}}]{}
\end{DoxyParamCaption}
)}\hypertarget{_mock_failure_test_8cpp_addf2efef7f65ebc4816e6e9adffee168}{}\label{_mock_failure_test_8cpp_addf2efef7f65ebc4816e6e9adffee168}


Mock\+Failure\+Test.\+cpp 파일의 221 번째 라인에서 정의되었습니다.


\begin{DoxyCode}
222 \{
223     call1->withName(\textcolor{stringliteral}{"foo"}).onObject((\textcolor{keywordtype}{void}*) 0x02);
224     call2->withName(\textcolor{stringliteral}{"foo"}).onObject((\textcolor{keywordtype}{void}*) 0x03);
225     call2->callWasMade(1);
226     call2->wasPassedToObject();
227     call3->withName(\textcolor{stringliteral}{"unrelated"});
228     addAllToList();
229 
230     \hyperlink{class_mock_unexpected_object_failure}{MockUnexpectedObjectFailure} failure(
      \hyperlink{class_utest_shell_afeb97f1f06324a42444c71b412655122}{UtestShell::getCurrent}(), \textcolor{stringliteral}{"foo"}, (\textcolor{keywordtype}{void}*)0x1, *list);
231     \hyperlink{_utest_macros_8h_ade1dda09c948fee9ceb853bc6dd5f3cb}{STRCMP\_EQUAL}(\hyperlink{_simple_string_8h_a0699d0e92f0abee2b3bdb9f254f90e51}{StringFromFormat} (
232                  \textcolor{stringliteral}{"MockFailure: Function called on an unexpected object: foo\(\backslash\)n"}
233                  \textcolor{stringliteral}{"\(\backslash\)tActual object for call has address: <%p>\(\backslash\)n"}
234                  \textcolor{stringliteral}{"\(\backslash\)tEXPECTED calls that DID NOT happen related to function: foo\(\backslash\)n"}
235                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)t(object address: %p)::foo -> no parameters\(\backslash\)n"}
236                  \textcolor{stringliteral}{"\(\backslash\)tACTUAL calls that DID happen related to function: foo\(\backslash\)n"}
237                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)t(object address: %p)::foo -> no parameters"},
238                  (\textcolor{keywordtype}{void}*) 0x01, (\textcolor{keywordtype}{void}*) 0x02, (\textcolor{keywordtype}{void}*) 0x03).asCharString(), failure.getMessage().
      \hyperlink{class_simple_string_af7c0efaf31f42553f05719903c830be1}{asCharString}());
239 \}
\end{DoxyCode}


이 함수 내부에서 호출하는 함수들에 대한 그래프입니다.\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{_mock_failure_test_8cpp_addf2efef7f65ebc4816e6e9adffee168_cgraph}
\end{center}
\end{figure}


\index{Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}!T\+E\+ST@{T\+E\+ST}}
\index{T\+E\+ST@{T\+E\+ST}!Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}}
\subsubsection[{\texorpdfstring{T\+E\+S\+T(\+Mock\+Failure\+Test, Mock\+Expected\+Object\+Didnt\+Happen\+Failure)}{TEST(MockFailureTest, MockExpectedObjectDidntHappenFailure)}}]{\setlength{\rightskip}{0pt plus 5cm}T\+E\+ST (
\begin{DoxyParamCaption}
\item[{Mock\+Failure\+Test}]{, }
\item[{{\bf Mock\+Expected\+Object\+Didnt\+Happen\+Failure}}]{}
\end{DoxyParamCaption}
)}\hypertarget{_mock_failure_test_8cpp_aca94e143af3b376fe013f99e92c378b7}{}\label{_mock_failure_test_8cpp_aca94e143af3b376fe013f99e92c378b7}


Mock\+Failure\+Test.\+cpp 파일의 241 번째 라인에서 정의되었습니다.


\begin{DoxyCode}
242 \{
243     call1->withName(\textcolor{stringliteral}{"foo"}).onObject((\textcolor{keywordtype}{void}*) 0x02);
244     call2->withName(\textcolor{stringliteral}{"foo"}).onObject((\textcolor{keywordtype}{void}*) 0x03);
245     call2->callWasMade(1);
246     call2->wasPassedToObject();
247     call3->withName(\textcolor{stringliteral}{"unrelated"});
248     addAllToList();
249 
250     \hyperlink{class_mock_expected_object_didnt_happen_failure}{MockExpectedObjectDidntHappenFailure} failure(
      \hyperlink{class_utest_shell_afeb97f1f06324a42444c71b412655122}{UtestShell::getCurrent}(), \textcolor{stringliteral}{"foo"}, *list);
251     \hyperlink{_utest_macros_8h_ade1dda09c948fee9ceb853bc6dd5f3cb}{STRCMP\_EQUAL}(\hyperlink{_simple_string_8h_a0699d0e92f0abee2b3bdb9f254f90e51}{StringFromFormat}(
252                  \textcolor{stringliteral}{"Mock Failure: Expected call on object for function \(\backslash\)"foo\(\backslash\)" but it did not happen.\(\backslash\)n"}
253                  \textcolor{stringliteral}{"\(\backslash\)tEXPECTED calls that DID NOT happen related to function: foo\(\backslash\)n"}
254                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)t(object address: %p)::foo -> no parameters\(\backslash\)n"}
255                  \textcolor{stringliteral}{"\(\backslash\)tACTUAL calls that DID happen related to function: foo\(\backslash\)n"}
256                  \textcolor{stringliteral}{"\(\backslash\)t\(\backslash\)t(object address: %p)::foo -> no parameters"},
257                  (\textcolor{keywordtype}{void}*) 0x2, (\textcolor{keywordtype}{void}*) 0x3).asCharString(), failure.getMessage().
      \hyperlink{class_simple_string_af7c0efaf31f42553f05719903c830be1}{asCharString}());
258 \}
\end{DoxyCode}


이 함수 내부에서 호출하는 함수들에 대한 그래프입니다.\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{_mock_failure_test_8cpp_aca94e143af3b376fe013f99e92c378b7_cgraph}
\end{center}
\end{figure}


\index{Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}!T\+E\+S\+T\+\_\+\+G\+R\+O\+UP@{T\+E\+S\+T\+\_\+\+G\+R\+O\+UP}}
\index{T\+E\+S\+T\+\_\+\+G\+R\+O\+UP@{T\+E\+S\+T\+\_\+\+G\+R\+O\+UP}!Mock\+Failure\+Test.\+cpp@{Mock\+Failure\+Test.\+cpp}}
\subsubsection[{\texorpdfstring{T\+E\+S\+T\+\_\+\+G\+R\+O\+U\+P(\+Mock\+Failure\+Test)}{TEST_GROUP(MockFailureTest)}}]{\setlength{\rightskip}{0pt plus 5cm}T\+E\+S\+T\+\_\+\+G\+R\+O\+UP (
\begin{DoxyParamCaption}
\item[{Mock\+Failure\+Test}]{}
\end{DoxyParamCaption}
)}\hypertarget{_mock_failure_test_8cpp_a3b989a8079863b123e286dfbeebad578}{}\label{_mock_failure_test_8cpp_a3b989a8079863b123e286dfbeebad578}


Mock\+Failure\+Test.\+cpp 파일의 34 번째 라인에서 정의되었습니다.


\begin{DoxyCode}
35 \{
36     \hyperlink{class_mock_failure_reporter}{MockFailureReporter} reporter;
37 
38     \hyperlink{class_mock_expected_calls_list}{MockExpectedCallsList} *list;
39     \hyperlink{class_mock_checked_expected_call}{MockCheckedExpectedCall}* call1;
40     \hyperlink{class_mock_checked_expected_call}{MockCheckedExpectedCall}* call2;
41     \hyperlink{class_mock_checked_expected_call}{MockCheckedExpectedCall}* call3;
42 
43     \textcolor{keywordtype}{void} setup ()
44     \{
45         list = \textcolor{keyword}{new} \hyperlink{class_mock_expected_calls_list}{MockExpectedCallsList};
46         call1 = \textcolor{keyword}{new} \hyperlink{class_mock_checked_expected_call}{MockCheckedExpectedCall};
47         call2 = \textcolor{keyword}{new} \hyperlink{class_mock_checked_expected_call}{MockCheckedExpectedCall};
48         call3 = \textcolor{keyword}{new} \hyperlink{class_mock_checked_expected_call}{MockCheckedExpectedCall};
49     \}
50     \textcolor{keywordtype}{void} teardown ()
51     \{
52         \textcolor{keyword}{delete} list;
53         \textcolor{keyword}{delete} call1;
54         \textcolor{keyword}{delete} call2;
55         \textcolor{keyword}{delete} call3;
56         \hyperlink{_mock_failure_reporter_for_test_8h_a2501f613605d8679f344e05fedffb3de}{CHECK\_NO\_MOCK\_FAILURE}();
57     \}
58     \textcolor{keywordtype}{void} addAllToList()
59     \{
60         list->\hyperlink{class_mock_expected_calls_list_a93aa2234c01260b1e76ceef59f8cfaee}{addExpectedCall}(call1);
61         list->\hyperlink{class_mock_expected_calls_list_a93aa2234c01260b1e76ceef59f8cfaee}{addExpectedCall}(call2);
62         list->\hyperlink{class_mock_expected_calls_list_a93aa2234c01260b1e76ceef59f8cfaee}{addExpectedCall}(call3);
63     \}
64 
65     \textcolor{keywordtype}{void} checkUnexpectedNthCallMessage(\textcolor{keywordtype}{unsigned} \textcolor{keywordtype}{int} count, \textcolor{keyword}{const} \textcolor{keywordtype}{char}* expectedOrdinal)
66     \{
67         \hyperlink{class_mock_expected_calls_list}{MockExpectedCallsList} callList;
68         \hyperlink{class_mock_checked_expected_call}{MockCheckedExpectedCall} expCall;
69 
70         expCall.\hyperlink{class_mock_checked_expected_call_a956e88393edbb7f7427eecb56ac5e317}{withName}(\textcolor{stringliteral}{"bar"});
71         \textcolor{keywordflow}{for} (\textcolor{keywordtype}{unsigned} \textcolor{keywordtype}{int} i = 0; i < (count - 1); i++) \{
72             expCall.\hyperlink{class_mock_checked_expected_call_a6e2b7989a09a51036edbafebda0e012a}{callWasMade}(1);
73             callList.\hyperlink{class_mock_expected_calls_list_a93aa2234c01260b1e76ceef59f8cfaee}{addExpectedCall}(&expCall);
74         \}
75 
76         \hyperlink{class_mock_unexpected_call_happened_failure}{MockUnexpectedCallHappenedFailure} failure(
      \hyperlink{class_utest_shell_afeb97f1f06324a42444c71b412655122}{UtestShell::getCurrent}(), \textcolor{stringliteral}{"bar"}, callList);
77 
78         \hyperlink{class_simple_string}{SimpleString} expectedMessage = \hyperlink{_simple_string_8h_a0699d0e92f0abee2b3bdb9f254f90e51}{StringFromFormat}(\textcolor{stringliteral}{"Mock Failure:
       Unexpected additional (%s) call to function: bar\(\backslash\)n\(\backslash\)tEXPECTED"}, expectedOrdinal);
79         \hyperlink{_utest_macros_8h_a13a6dd463439a53bd882a77f86550b1c}{STRCMP\_CONTAINS}(expectedMessage.\hyperlink{class_simple_string_af7c0efaf31f42553f05719903c830be1}{asCharString}(), failure.getMessage().
      asCharString());
80     \}
81 \};
\end{DoxyCode}


이 함수 내부에서 호출하는 함수들에 대한 그래프입니다.\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{_mock_failure_test_8cpp_a3b989a8079863b123e286dfbeebad578_cgraph}
\end{center}
\end{figure}


